[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npx prisma generate && npx nest build"

[deploy]
startCommand = "node dist/main.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
